"""initial schema v2

Revision ID: 0b1df16866d6
Revises: 
Create Date: 2026-08-22 00:34:07.380678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b1df16866d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('persona', sa.Enum('aggressive_d2c', 'relationship_b2b', 'neutral_midmarket', name='merchantpersona'), nullable=False),
    sa.Column('stopping_aggressiveness', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precedents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_persona', sa.Enum('aggressive_d2c', 'relationship_b2b', 'neutral_midmarket', name='merchantpersona'), nullable=False),
    sa.Column('failure_class', sa.Enum('insufficient_funds', 'expired_card', 'bank_timeout', 'risk_decline', 'mandate_failure', name='failureclass'), nullable=False),
    sa.Column('case_summary', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.Enum('retry_now', 'retry_scheduled', 'update_payment_method_flow', 'mandate_reauth', 'whatsapp_nudge', 'hinglish_voice_call', 'escalate_human', 'stop_chasing', name='actiontype'), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('recovered_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('razorpay_error_code', sa.String(), nullable=False),
    sa.Column('razorpay_error_reason', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('failure_class', sa.Enum('insufficient_funds', 'expired_card', 'bank_timeout', 'risk_decline', 'mandate_failure', name='failureclass'), nullable=True),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('expected_recovery_value', sa.Float(), nullable=True),
    sa.Column('probability_of_success', sa.Float(), nullable=True),
    sa.Column('annoyance_cost', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'scored', 'action_recommended', 'action_executed', 'recovered', 'stopped', 'exhausted', name='failurestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions_taken',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('retry_now', 'retry_scheduled', 'update_payment_method_flow', 'mandate_reauth', 'whatsapp_nudge', 'hinglish_voice_call', 'escalate_human', 'stop_chasing', name='actiontype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('recovered_amount', sa.Float(), nullable=True),
    sa.Column('cost_incurred', sa.Float(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('failure_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['failure_id'], ['failures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('actions_taken')
    op.drop_table('failures')
    op.drop_table('precedents')
    op.drop_table('merchants')
    # ### end Alembic commands ###
