"""add promise to pay tracking fields

Revision ID: 18b55a0df465
Revises: b8224b3eca06
Create Date: 2026-08-31 12:47:11.076214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b55a0df465'
down_revision: Union[str, Sequence[str], None] = 'b8224b3eca06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failures', sa.Column('promised_payment_date', sa.DateTime(), nullable=True))
    op.add_column('failures', sa.Column('promise_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('failures', 'promise_status')
    op.drop_column('failures', 'promised_payment_date')
    # ### end Alembic commands ###
