"""add api_key_hash to merchants

Revision ID: 33ac97825135
Revises: a08736f9e29b
Create Date: 2026-08-30 12:51:26.512873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ac97825135'
down_revision: Union[str, Sequence[str], None] = 'a08736f9e29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('api_key_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'merchants', ['api_key_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    op.drop_column('merchants', 'api_key_hash')
    # ### end Alembic commands ###
