"""add bandit state and batch history tables

Revision ID: 5df1877b42fa
Revises: 0b1df16866d6
Create Date: 2026-08-22 19:31:36.784470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5df1877b42fa'
down_revision: Union[str, Sequence[str], None] = '0b1df16866d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_run_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('chase_capacity', sa.Integer(), nullable=True),
    sa.Column('aggressiveness_used', sa.Float(), nullable=False),
    sa.Column('arm_index_used', sa.Integer(), nullable=False),
    sa.Column('context_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_batch_value', sa.Float(), nullable=False),
    sa.Column('total_expected_recovery', sa.Float(), nullable=False),
    sa.Column('total_simulated_recovered', sa.Float(), nullable=False),
    sa.Column('total_annoyance_cost', sa.Float(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('chased_count', sa.Integer(), nullable=False),
    sa.Column('stopped_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_bandit_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('arms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('a_matrices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('b_vectors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_batches_run', sa.Integer(), nullable=True),
    sa.Column('current_best_arm_index', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant_bandit_state')
    op.drop_table('batch_run_history')
    # ### end Alembic commands ###
